version: '3.9'
services:
  frontend:
    image: docker.laurel.k12.mt.us/lps-facilities
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    # environment:
    #   - NEXTAUTH_SECRET
    #   - NEXT_PUBLIC_AZURE_AD_CLIENT_ID
    #   - NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET
    #   - NEXT_PUBLIC_AZURE_TENANT_ID
    #   - NEXT_PUBLIC_AZURE_AUTHORITY
    #   - NEXTAUTH_URL
    #   - CAL_API_KEY
    #   - DATABASE_URL
    #   - GMAIL_USER
    #   - GMAIL_PASSWORD
    #   - HOSTNAME
    #   - PORT
    #   - HOST
    #   - NEXT_PUBLIC_HOST
    #   - NEXT_PUBLIC_SQUARE_APP_ID
    #   - NEXT_PUBLIC_SQUARE_LOCATION_ID
    #   - NEXT_PUBLIC_SQUARE_TOKEN
    #   - GOOGLE_CAL_USER
    #   - GOOGLE_CAL_PASS
    #   - GOOGLE_CLIENT_ID
    #   - GOOGLE_CLIENT_SECRET
    #   - GOOGLE_ACCESS_TOKEN
    #   - GOOGLE_REFRESH_TOKEN
    #   - JIRA_USER
    #   - JIRA_API
    #   - S3_PASSWORD
    #   - S3_ACCESS_KEY
    #   - S3_SECRET
    #   - S3_HOST
    #   - S3_URL
